
default_language_version:
        python: python3

repos:

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
        exclude: '^(third_party)/'
    -   id: check-json
        exclude: '.devcontainer/devcontainer.json' # this supports JSON with comments
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-added-large-files
        args: ['--maxkb=100']

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat .
        language_version: python3


  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln

  - repo: https://github.com/isidentical/teyit
    rev: 0.4.3
    hooks:
      - id: teyit


  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        name: validate poetry lock
        args:
        - --check


  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        exclude: '^(third_party/)|(poetry.lock)'
        args:
        # if you've got a short variable name that's getting flagged, add it here
        - -L bu,ro,te,ue,alo,hda,ois,nam,nams,ned,som,parm,setts,inout,warmup,bumb,nd,sie
        - --builtins clear,rare,informal,usage,code,names,en-GB_to_en-US
